dev-demo: don't throw an error, if pull_repos task can't pull some repo
https://web.tracklify.com/project/2b7ZVgE5/AdminForth/1343/UN5WBbUP/can-we-just-skip-adapters-or-p

diff --git a/dev-demo/Taskfile.yaml b/dev-demo/Taskfile.yaml
--- a/dev-demo/Taskfile.yaml
+++ b/dev-demo/Taskfile.yaml
@@ -74,7 +74,7 @@ tasks:
 
           if [ -d "${name}" ]; then
             echo "Pulling ${name}"
-            (cd "${name}" && git pull)
+            (cd "${name}" && git pull || echo "Failed to pull ${name}")
           else
             echo "Cloning ${name}"
             git clone "${repo_url}" "${name}"
